/**
 * @file Automatically generated by barrelsby.
 */

export * from './area.spec.js';
export * from './bar.spec.js';
export * from './bubble.spec.js';
export * from './pie.spec.js';
export * from './simple-bar.spec.js';
