packages:
  - "modules/*"

allowBuilds:
  canvas: true
  better-sqlite3: true
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  cpu-features: true
  esbuild: true
  ssh2: true
