packages:
  - "modules/*"

peerDependencyRules:
  allowedVersions:
    typescript: 7.0.2

allowBuilds:
  canvas: true
  better-sqlite3: true
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  cpu-features: true
  esbuild: true
  ssh2: true

overrides:
  axios: ^1.18.0
  basic-ftp: ^5.3.1
  "@babel/traverse": ^7.23.2
  "@smithy/types": ^2.3.3
  "@protobufjs/utf8": ^1.1.1
  body-parser: ^1.20.3
  cheerio: ^1.0.0
  cookie: ^0.7.0
  cross-spawn: ^7.0.6
  diff: ^5.2.2
  js-yaml: ^4.3.0
  express: ^4.20.0
  fast-xml-parser: ^5.7.0
  flatted: ^3.4.2
  follow-redirects: ^1.16.0
  micromatch: ^4.0.8
  minimatch: ^10.2.4
  glob@10.x: ^10.5.0
  glob@11.x: ^11.1.0
  ip-address: ^10.1.1
  lodash: ^4.17.23
  nanoid: ^3.3.8
  nth-check: ^2.0.1
  sha.js: ^2.4.2
  semver: ^7.5.2
  path-to-regexp: ^0.1.13
  picomatch: ^2.3.2
  postcss: ^8.5.23
  qs: ^6.14.2
  rollup: ^4.59.0
  sanitize-html: ^2.12.1
  send: ^0.19.0
  serve-static: ^1.16.0
  tar: ^7.5.11
  tar-fs: ^2.1.4
  tmp: ^0.2.7
  underscore: ^1.13.7
  undici: ^6.24.0
  uuid: 11.1.1
  vite: 7.3.2
  yaml: ^2.8.3
