/* tslint:disable */
/* eslint-disable */
/**
 * Sobol API Docs
 * An OpenAPI Implementation exposing Sobol\'s RESTful API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@sobol.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AddressTypeInternalEnum {
    address = 'address',
    contract = 'contract',
    gnosis_safe = 'gnosis_safe'
}


export function AddressTypeInternalEnumFromJSON(json: any): AddressTypeInternalEnum {
    return AddressTypeInternalEnumFromJSONTyped(json, false);
}

export function AddressTypeInternalEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressTypeInternalEnum {
    return json as AddressTypeInternalEnum;
}

export function AddressTypeInternalEnumToJSON(value?: AddressTypeInternalEnum | null): any {
    return value as any;
}

