/* tslint:disable */
/* eslint-disable */
/**
 * Sobol API Docs
 * An OpenAPI Implementation exposing Sobol\'s RESTful API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@sobol.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GlobalIdentity
 */
export interface GlobalIdentity {
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _id: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _type: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof GlobalIdentity
     */
    _createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GlobalIdentity
     */
    _updatedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _updatedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof GlobalIdentity
     */
    _archivedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _archivedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof GlobalIdentity
     */
    _deletedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _deletedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    _operationId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GlobalIdentity
     */
    _signedTerms?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    identityId: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    displayId?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    type: GlobalIdentityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    validatedBy: GlobalIdentityValidatedByEnum;
    /**
     * 
     * @type {string}
     * @memberof GlobalIdentity
     */
    orgId?: string;
}

/**
* @export
* @enum {string}
*/
export enum GlobalIdentityTypeEnum {
    email = 'email',
    discord = 'discord',
    eth_wallet = 'eth_wallet'
}
/**
* @export
* @enum {string}
*/
export enum GlobalIdentityValidatedByEnum {
    saml = 'saml',
    google = 'google',
    passwordless = 'passwordless',
    discord = 'discord',
    eth_wallet = 'eth_wallet',
    enterprise_admin = 'enterprise_admin'
}


/**
 * Check if a given object implements the GlobalIdentity interface.
 */
export function instanceOfGlobalIdentity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "_id" in value;
    isInstance = isInstance && "_type" in value;
    isInstance = isInstance && "_createdBy" in value;
    isInstance = isInstance && "identityId" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "validatedBy" in value;

    return isInstance;
}

export function GlobalIdentityFromJSON(json: any): GlobalIdentity {
    return GlobalIdentityFromJSONTyped(json, false);
}

export function GlobalIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalIdentity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_id': json['_id'],
        '_type': json['_type'],
        '_createdBy': json['_createdBy'],
        '_createdOn': !exists(json, '_createdOn') ? undefined : (new Date(json['_createdOn'])),
        '_updatedOn': !exists(json, '_updatedOn') ? undefined : (new Date(json['_updatedOn'])),
        '_updatedBy': !exists(json, '_updatedBy') ? undefined : json['_updatedBy'],
        '_archivedOn': !exists(json, '_archivedOn') ? undefined : (new Date(json['_archivedOn'])),
        '_archivedBy': !exists(json, '_archivedBy') ? undefined : json['_archivedBy'],
        '_deletedOn': !exists(json, '_deletedOn') ? undefined : (new Date(json['_deletedOn'])),
        '_deletedBy': !exists(json, '_deletedBy') ? undefined : json['_deletedBy'],
        '_operationId': !exists(json, '_operationId') ? undefined : json['_operationId'],
        '_signedTerms': !exists(json, '_signedTerms') ? undefined : json['_signedTerms'],
        'identityId': json['identityId'],
        'displayId': !exists(json, 'displayId') ? undefined : json['displayId'],
        'type': json['type'],
        'validatedBy': json['validatedBy'],
        'orgId': !exists(json, 'orgId') ? undefined : json['orgId'],
    };
}

export function GlobalIdentityToJSON(value?: GlobalIdentity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value._id,
        '_type': value._type,
        '_createdBy': value._createdBy,
        '_createdOn': value._createdOn === undefined ? undefined : (value._createdOn.toISOString()),
        '_updatedOn': value._updatedOn === undefined ? undefined : (value._updatedOn.toISOString()),
        '_updatedBy': value._updatedBy,
        '_archivedOn': value._archivedOn === undefined ? undefined : (value._archivedOn.toISOString()),
        '_archivedBy': value._archivedBy,
        '_deletedOn': value._deletedOn === undefined ? undefined : (value._deletedOn.toISOString()),
        '_deletedBy': value._deletedBy,
        '_operationId': value._operationId,
        '_signedTerms': value._signedTerms,
        'identityId': value.identityId,
        'displayId': value.displayId,
        'type': value.type,
        'validatedBy': value.validatedBy,
        'orgId': value.orgId,
    };
}

