/* tslint:disable */
/* eslint-disable */
/**
 * Sobol API Docs
 * An OpenAPI Implementation exposing Sobol\'s RESTful API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@sobol.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LocalIdentity
 */
export interface LocalIdentity {
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _id: string;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _type?: LocalIdentityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _rootId: string;
    /**
     * 
     * @type {Date}
     * @memberof LocalIdentity
     */
    _createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof LocalIdentity
     */
    _updatedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _updatedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof LocalIdentity
     */
    _archivedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _archivedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof LocalIdentity
     */
    _deletedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _deletedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    _operationId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LocalIdentity
     */
    _isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    identityId: string;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    displayId?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    type: LocalIdentityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LocalIdentity
     */
    globalIdentityId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LocalIdentity
     */
    isRequired?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum LocalIdentityTypeEnum {
    local_identity = 'local_identity'
}
/**
* @export
* @enum {string}
*/
export enum LocalIdentityTypeEnum {
    email = 'email',
    discord = 'discord',
    eth_wallet = 'eth_wallet'
}


/**
 * Check if a given object implements the LocalIdentity interface.
 */
export function instanceOfLocalIdentity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "_id" in value;
    isInstance = isInstance && "_rootId" in value;
    isInstance = isInstance && "_createdBy" in value;
    isInstance = isInstance && "identityId" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function LocalIdentityFromJSON(json: any): LocalIdentity {
    return LocalIdentityFromJSONTyped(json, false);
}

export function LocalIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalIdentity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_id': json['_id'],
        '_type': !exists(json, '_type') ? undefined : json['_type'],
        '_rootId': json['_rootId'],
        '_createdOn': !exists(json, '_createdOn') ? undefined : (new Date(json['_createdOn'])),
        '_createdBy': json['_createdBy'],
        '_updatedOn': !exists(json, '_updatedOn') ? undefined : (new Date(json['_updatedOn'])),
        '_updatedBy': !exists(json, '_updatedBy') ? undefined : json['_updatedBy'],
        '_archivedOn': !exists(json, '_archivedOn') ? undefined : (new Date(json['_archivedOn'])),
        '_archivedBy': !exists(json, '_archivedBy') ? undefined : json['_archivedBy'],
        '_deletedOn': !exists(json, '_deletedOn') ? undefined : (new Date(json['_deletedOn'])),
        '_deletedBy': !exists(json, '_deletedBy') ? undefined : json['_deletedBy'],
        '_operationId': !exists(json, '_operationId') ? undefined : json['_operationId'],
        '_isPublic': !exists(json, '_isPublic') ? undefined : json['_isPublic'],
        'identityId': json['identityId'],
        'displayId': !exists(json, 'displayId') ? undefined : json['displayId'],
        'type': json['type'],
        'globalIdentityId': !exists(json, 'globalIdentityId') ? undefined : json['globalIdentityId'],
        'isRequired': !exists(json, 'isRequired') ? undefined : json['isRequired'],
    };
}

export function LocalIdentityToJSON(value?: LocalIdentity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value._id,
        '_type': value._type,
        '_rootId': value._rootId,
        '_createdOn': value._createdOn === undefined ? undefined : (value._createdOn.toISOString()),
        '_createdBy': value._createdBy,
        '_updatedOn': value._updatedOn === undefined ? undefined : (value._updatedOn.toISOString()),
        '_updatedBy': value._updatedBy,
        '_archivedOn': value._archivedOn === undefined ? undefined : (value._archivedOn.toISOString()),
        '_archivedBy': value._archivedBy,
        '_deletedOn': value._deletedOn === undefined ? undefined : (value._deletedOn.toISOString()),
        '_deletedBy': value._deletedBy,
        '_operationId': value._operationId,
        '_isPublic': value._isPublic,
        'identityId': value.identityId,
        'displayId': value.displayId,
        'type': value.type,
        'globalIdentityId': value.globalIdentityId,
        'isRequired': value.isRequired,
    };
}

