/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * list of blocked domains
 * @export
 * @interface GetBlockedDomains
 */
export interface GetBlockedDomains {
    /**
     * List of all blocked domains
     * @type {Array<string>}
     * @memberof GetBlockedDomains
     */
    domains: Array<string>;
}

/**
 * Check if a given object implements the GetBlockedDomains interface.
 */
export function instanceOfGetBlockedDomains(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "domains" in value;

    return isInstance;
}

export function GetBlockedDomainsFromJSON(json: any): GetBlockedDomains {
    return GetBlockedDomainsFromJSONTyped(json, false);
}

export function GetBlockedDomainsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockedDomains {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domains': json['domains'],
    };
}

export function GetBlockedDomainsToJSON(value?: GetBlockedDomains | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domains': value.domains,
    };
}

