/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * Credits remaining for child account
 * @export
 * @interface RemainingCreditModelChild
 */
export interface RemainingCreditModelChild {
    /**
     * SMS Credits remaining for child account
     * @type {number}
     * @memberof RemainingCreditModelChild
     */
    sms: number;
    /**
     * Email Credits remaining for child account
     * @type {number}
     * @memberof RemainingCreditModelChild
     */
    email: number;
}

/**
 * Check if a given object implements the RemainingCreditModelChild interface.
 */
export function instanceOfRemainingCreditModelChild(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sms" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function RemainingCreditModelChildFromJSON(json: any): RemainingCreditModelChild {
    return RemainingCreditModelChildFromJSONTyped(json, false);
}

export function RemainingCreditModelChildFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemainingCreditModelChild {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sms': json['sms'],
        'email': json['email'],
    };
}

export function RemainingCreditModelChildToJSON(value?: RemainingCreditModelChild | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sms': value.sms,
        'email': value.email,
    };
}

