/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SendSmtpEmailAttachmentInner
 */
export interface SendSmtpEmailAttachmentInner {
    /**
     * Absolute url of the attachment (no local file).
     * @type {string}
     * @memberof SendSmtpEmailAttachmentInner
     */
    url?: string;
    /**
     * Base64 encoded chunk data of the attachment generated on the fly
     * @type {string}
     * @memberof SendSmtpEmailAttachmentInner
     */
    content?: string;
    /**
     * Required if content is passed. Name of the attachment
     * @type {string}
     * @memberof SendSmtpEmailAttachmentInner
     */
    name?: string;
}

/**
 * Check if a given object implements the SendSmtpEmailAttachmentInner interface.
 */
export function instanceOfSendSmtpEmailAttachmentInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendSmtpEmailAttachmentInnerFromJSON(json: any): SendSmtpEmailAttachmentInner {
    return SendSmtpEmailAttachmentInnerFromJSONTyped(json, false);
}

export function SendSmtpEmailAttachmentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendSmtpEmailAttachmentInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SendSmtpEmailAttachmentInnerToJSON(value?: SendSmtpEmailAttachmentInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'content': value.content,
        'name': value.name,
    };
}

