/**
 * @file Automatically generated by barrelsby.
 */

export * from './components/warden-user-profile/warden-user-profile.component';
export * from './components/warden-user-profile/warden-user-profile.module';
